# Generated by Django 5.2.5 on 2025-08-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, upload_to='sneakers/'),
        ),
    ]
