# Generated by Django 5.2.5 on 2025-08-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_shoes', '0004_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Personalizacion',
        ),
    ]
