# Generated by Django 5.2.5 on 2025-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_shoes', '0006_carrito_user_comment_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(default='Marca desconocida', max_length=100),
        ),
    ]
